import * as React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Sora } from "next/font/google";
import ReactQueryProvider from "@/components/react-query-provider";

const fontSans = Sora({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html className={`${fontSans.variable}`} lang="en">
			<body className={"max-w-md mx-auto antialiased"}>
				<ReactQueryProvider>
					{children}
				</ReactQueryProvider>
			</body>
		</html>
	);
}
